
<div class="container category_list" id="content">
    <div class="clearfix">
        <!--        <div class="search-bar pull-left">-->
        <!--            <span class="lead">--><?php //echo $category->getName(); ?><!--</span>-->
        <!--        </div>-->
        <div class="dropdown pull-right">
            <span class="sort_by">Sort by: </span>
            <select class="btn btn-default" onchange="location='/category/view/<?php echo $category->getId() ?>' + this.value;">
                <option>None</option>
                <option value="?sort=htl" <?= $sort == 'htl' ? ' selected="selected"' : '';?>>Price High to Low</option>
                <option value="?sort=lth" <?= $sort == 'lth' ? ' selected="selected"' : '';?>>Price Low to High</option>
                <option value="?sort=sell" <?= $sort == 'sell' ? ' selected="selected"' : '';?>>Best Sell</option>
                <option value="?sort=new" <?= $sort == 'new' ? ' selected="selected"' : '';?>>Newest Items</option>
            </select>
        </div>
    </div>

    <div class="row clearfix mt15">
        <?php include_once 'view/_sidebar.phtml' ?>
        <?php include_once 'view/_listProduct.phtml' ?>
    </div>
</div>