<div class="track-form" v-if="track_form">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
                <md-card class="md-transparent">
                    <md-card-area>
                        <md-card-header>
                            <div class="md-title">Track your order</div>
                            <!--                                    <div class="md-subhead">Use order id</div>-->
                        </md-card-header>

                        <md-card-content>
                            <md-input-container :class="[errors.has('email') ? 'md-input-invalid' : '']">
                                <label>Email</label>
                                <md-input name="email"
                                          v-model="email"
                                          v-validate="'required|email'">
                                </md-input>
                                <span class="md-error"
                                      v-show="errors.has('email')">
                                            {{ errors.first('email') }}
                                        </span>
                            </md-input-container>

                            <md-input-container :class="[errors.has('phone number') ? 'md-input-invalid' : '']">
                                <label>Phone number</label>
                                <md-input name="phone number"
                                          v-model="phone_number"
                                          v-validate="'required|numeric'">
                                </md-input>
                                <span class="md-error"
                                      v-show="errors.has('phone number')">
                                            {{ errors.first('phone number') }}
                                        </span>
                            </md-input-container>
                        </md-card-content>
                    </md-card-area>

                    <md-card-actions>
                        <md-button class="md-primary md-raised"
                                   @click="tracking">
                            Tracking
                        </md-button>
                    </md-card-actions>
                </md-card>
            </div>
        </div>
    </div>
</div>
