<div class="box">
    <div class="box-header">
        <h2 class="box-title">Order Chart</h2>
        <select class="form-control select-box" id="order-select">
        	<option value="1">Current Month</option>
        	<option value="2">Current year</option>
        </select>
    </div>
    <div class="box-body">
        <div id="order-chart" width="400" height="400"></div>
    </div>
</div>

<div class="box">
    <div class="box-header">
        <h2 class="box-title">Review Chart</h2>
        <select class="form-control select-box" id="review-select">
        	<option value="1">Current Month</option>
        	<option value="2">Current year</option>
        </select>
    </div>
    <div class="box-body">
        <div id="review-chart" width="400" height="400"></div>
    </div>
</div>
