<div class="row">
    <div class="col-md-6">
        <?php include_once '_money-chart.phtml' ?>
    </div>
    <div class="col-md-6">
        <?php include_once '_order-chart.phtml' ?>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <?php include_once '_user-chart.phtml' ?>
    </div>
    
    <div class="col-md-6">
        <?php include_once '_review-chart.phtml' ?>
    </div>
</div>

