<table id="example-1" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th style="width: 15px">#</th>
            <th>Name</th>
            <th>Image</th>
            <th>Category</th>
            <th>Option</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach($products_in_trash as $product): ?>
        
        <tr>
            <td><?php echo ++$i ?></td>
            <td>                    
                <a href="<?= $this->url('products',
                    ['action' => 'view', 'id' => $product->getId()]) ?>">
                    <?php echo $product->getName(); ?>
                </a>
            </td>
            <td>
                <img src="<?php echo $this->basePath($product->getImage()) ?>" class="image_product">
            </td>
            <td>
                <?php if ($product->getCategory() != null){ ?>
                    <a href="<?= $this->url('categories',
                        ['action' => 'view', 'id' => $product->getCategory()->getId()]) ?>">
                        <?php echo $product->getCategory()->getName(); ?>
                    </a>
                <?php } ?>
            </td>
    
            <td>
                <a href="<?= $this->url('products',
                    ['action' => 'restore', 'id' => $product->getId()]) ?>" title="Restore">
                    <i class="fa fa-reply"></i>    
                </a>
                <a href="<?= $this->url('products',
                    ['action' => 'harddelete', 'id' => $product->getId()]) ?>" title="Remove from trash">
                    <i class="fa fa-trash" ></i>    
                </a>

            </td>
        </tr>
    <?php endforeach; ?>    
    </tbody>
</table>
